version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: surveyuser
      POSTGRES_PASSWORD: surveypass
      POSTGRES_DB: surveydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
    environment:
      - DATABASE_URL=postgresql+psycopg2://surveyuser:surveypass@db:5432/surveydb
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  pgdata: 